// <auto-generated />
using System;
using AjudaSolidaria.Respository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace AjudaSolidaria.Respository.Migrations
{
    [DbContext(typeof(AjudaSolidariaContext))]
    partial class AjudaSolidariaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("AjudaSolidaria.Domain.Pessoa", b =>
                {
                    b.Property<Guid>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("key")
                        .HasColumnType("uuid");

                    b.Property<string>("Bairro")
                        .HasColumnName("bairro")
                        .HasColumnType("text");

                    b.Property<string>("CPF")
                        .HasColumnName("cpf")
                        .HasColumnType("bpchar(11)");

                    b.Property<string>("Cep")
                        .HasColumnName("cep")
                        .HasColumnType("text");

                    b.Property<string>("Cidade")
                        .HasColumnName("cidade")
                        .HasColumnType("text");

                    b.Property<string>("Coordenadas")
                        .HasColumnName("coordenadas")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("created_at")
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("current_timestamp");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnName("data_nascimento")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Endereco")
                        .HasColumnName("endereco")
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .HasColumnName("estado")
                        .HasColumnType("bpchar(2)");

                    b.Property<string>("Nome")
                        .HasColumnName("nome")
                        .HasColumnType("character varying(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Numero")
                        .HasColumnName("numero")
                        .HasColumnType("text");

                    b.Property<bool>("Status")
                        .HasColumnName("status")
                        .HasColumnType("boolean");

                    b.Property<string>("Telefone")
                        .HasColumnName("telefone")
                        .HasColumnType("bpchar(11)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("updated_at")
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("current_timestamp");

                    b.HasKey("Key")
                        .HasName("pk_pessoa");

                    b.ToTable("pessoa");
                });
#pragma warning restore 612, 618
        }
    }
}
